name: symptom_triage_analytics
version: 1.0.0
config-version: 2

profile: symptom_triage_analytics

model-paths: ["models"]
macro-paths: ["macros"]
seed-paths: ["seeds"]
snapshot-paths: ["snapshots"]
analysis-paths: ["analyses"]
test-paths: ["tests"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  symptom_triage_analytics:
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    marts:
      +materialized: table

